wandb_version: 1

num_channels:
  desc: null
  value: null
max_L:
  desc: null
  value: null
correlation:
  desc: null
  value: 3
lr:
  desc: null
  value: 0.01
swa_lr:
  desc: null
  value: 0.001
weight_decay:
  desc: null
  value: 5.0e-07
batch_size:
  desc: null
  value: 10
max_num_epochs:
  desc: null
  value: 50
start_swa:
  desc: null
  value: null
energy_weight:
  desc: null
  value: 1.0
forces_weight:
  desc: null
  value: 100.0
_wandb:
  desc: null
  value:
    python_version: 3.12.2
    cli_version: 0.17.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1721139179
    t:
      1:
      - 1
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.12.2
      5: 0.17.4
      8:
      - 5
      13: linux-x86_64
